import {
  heroImageDesktop,
  heroImageMobile,
  photo1,
  photo2,
  photo3,
  photo4,
  foto1,
  foto2,
  foto3,
  foto4,
  foto5,
  foto6,
  foto7,
  foto8,
  foto9,
  FaEnvelope,
  FaPhoneAlt,
  mail,
  phone,
  gallery1,
  gallery2,
  gallery3,
  gallery4,
  gallery5,
  gallery6,
  gallery7,
  gallery8,
  gallery9,
  gallery10,
  gallery11,
  gallery12,
  gallery13,
  gallery14,
  gallery15,
  gallery16,
  gallery17,
  gallery18,
  gallery19,
  gallery20,
  gallery21,
  gallery22,
  gallery23,
  gallery24,
  gallery25,
  gallery26,
  gallery27,
  gallery28,
  gallery29,
  gallery30,
  gallery31,
  gallery32,
  gallery33,
  gallery34,
  gallery35,
  gallery36,
  gallery37,
  gallery38,
  gallery39,
  gallery40,
  gallery41,
  gallery42,
  gallery43,
  gallery44,
  gallery45,
  gallery46,
  gallery47,
  gallery48,
  gallery49,
  gallery50,
  gallery51,
  gallery52,
  gallery53,
  gallery54,
  gallery55,
  gallery56,
  gallery57,
  gallery58,
  gallery59,
  gallery60,
} from "../assets";

const priceList = [
  {
    id: 1,
    name: "Pomiary instalacji fotowoltaicznych",
    description:
      "Pomiary strony DC i AC, pomiary napięć i strat modułów fotowoltaicznych, rezystancje izolacji, rezystancje uziemienia. Dodatkowo analiza strat uzysków instalacji względem projektów.",
    details: [
      "Pomiary strony DC",
      "Pomiary napięć i strat modułów fotowoltaicznych",
      "Rezystancja izolacji",
      "Rezystancja uziemienia",
      "Pomiary strony AC (zabezpieczenia różnicowo-prądowe i nadprądowe)",
      "Interpretacja strat uzysków względem projektów",
    ],
    regions: [
      {
        region: "opolskie",
        priceBrutto: "do negocjacji",
      },
      {
        region: "śląskie / dolnośląskie",
        priceBrutto: "do negocjacji",
        priceNetto: null,
      },
    ],
    imagePath: foto7,
    thumbnailPath: foto7,
  },
  {
    id: 2,
    name: "Odbiory instalacji fotowoltaicznych jako niezależny inspektor",
    description:
      "Pomiary elektryczne, interpretacja doboru konstrukcji, sprawdzanie prawidłowości montażu.",
    details: [
      "Pomiary elektryczne",
      "Interpretacja doboru konstrukcji",
      "Sprawdzanie prawidłowości montażu",
    ],
    regions: [
      {
        region: "opolskie",
        priceBrutto: "do negocjacji",
        priceNetto: null,
      },
      {
        region: "śląskie / dolnośląskie",
        priceBrutto: "do negocjacji",
        priceNetto: null,
      },
    ],
    imagePath: foto9,
    thumbnailPath: foto9,
  },
  {
    id: 3,
    name: "Pomiary instalacji elektrycznej w domach jednorodzinnych",
    description:
      "Pomiary punktów przyłącza oraz pomiary rezystancji uziemienia dla domów jednorodzinnych.",
    details: [
      "Pomiary punktów przyłącza (15 zł netto od punktu)",
      "Pomiary rezystancji uziemienia",
    ],
    regions: [
      {
        region: "Cała Polska",
        priceBrutto: "do negocjacji",
        priceNetto: null,
      },
      {
        region: "Rezystancja uziemienia",
        priceBrutto: "do negocjacji",
        priceNetto: null,
      },
    ],
    imagePath: foto8,
    thumbnailPath: foto8,
  },
];

const contactInfo = {
  title: "Kontakt",
  address: {
    street: "Stefana Okrzei 11/9",
    city: "45-713 Opole",
  },
  phone: {
    icon: phone,
    number: "503 416 319",
  },
  email: {
    icon: mail,
    address: "banach@g-wat.pl",
  },
};

const allImages = [
  {
    src: gallery1,
    alt: "Instalacja paneli fotowoltaicznych na dachu",
    width: 640,
    height: 427,
  },
  {
    src: gallery2,
    alt: "Panele fotowoltaiczne na dachu domu",
    width: 640,
    height: 427,
  },
  {
    src: gallery3,
    alt: "Instalacja paneli słonecznych na dachu",
    width: 640,
    height: 427,
  },
  {
    src: gallery4,
    alt: "System fotowoltaiczny na dachu budynku",
    width: 640,
    height: 427,
  },
  { src: gallery5, alt: "Dom z panelami słonecznymi", width: 640, height: 427 },
  {
    src: gallery6,
    alt: "Instalacja paneli na dachu budynku mieszkalnego",
    width: 640,
    height: 427,
  },
  {
    src: gallery7,
    alt: "Dom z zamontowanymi panelami fotowoltaicznymi",
    width: 640,
    height: 427,
  },
  {
    src: gallery8,
    alt: "System paneli słonecznych na posesji",
    width: 640,
    height: 427,
  },
  {
    src: gallery9,
    alt: "Panele słoneczne na podwórku",
    width: 640,
    height: 427,
  },
  {
    src: gallery10,
    alt: "Instalacja paneli na budynku gospodarczym",
    width: 640,
    height: 427,
  },
  {
    src: gallery11,
    alt: "Budowa paneli fotowoltaicznych na posesji",
    width: 640,
    height: 427,
  },
  {
    src: gallery12,
    alt: "Instalacja elektryczna z urządzeniami pomiarowymi",
    width: 640,
    height: 427,
  },
  {
    src: gallery13,
    alt: "Pomiary instalacji elektrycznej na miejscu",
    width: 640,
    height: 427,
  },
  {
    src: gallery14,
    alt: "Proces pomiaru instalacji elektrycznej",
    width: 640,
    height: 427,
  },
  {
    src: gallery15,
    alt: "Badanie termowizyjne instalacji elektrycznej",
    width: 640,
    height: 427,
  },
  {
    src: gallery16,
    alt: "Pomiary instalacji fotowoltaicznej",
    width: 640,
    height: 427,
  },
  {
    src: gallery17,
    alt: "Instalacja kabli do systemu fotowoltaicznego",
    width: 640,
    height: 427,
  },
  {
    src: gallery18,
    alt: "Podłączanie kabli fotowoltaicznych",
    width: 640,
    height: 427,
  },
  {
    src: gallery19,
    alt: "Widok z bliska na instalację paneli słonecznych",
    width: 640,
    height: 427,
  },
  {
    src: gallery20,
    alt: "Montaż paneli fotowoltaicznych na dachu",
    width: 640,
    height: 427,
  },
  {
    src: gallery21,
    alt: "Pomiar elektryczny z wykorzystaniem mierników",
    width: 640,
    height: 427,
  },
  {
    src: gallery22,
    alt: "Instalacja elektryczna z rozdzielnią",
    width: 640,
    height: 427,
  },
  {
    src: gallery23,
    alt: "Pomiary elektryczne rozdzielni",
    width: 640,
    height: 427,
  },
  {
    src: gallery24,
    alt: "Rozdzielnia elektryczna z urządzeniami pomiarowymi",
    width: 640,
    height: 427,
  },
  {
    src: gallery25,
    alt: "Rozdzielnia z urządzeniami pomiarowymi i zabezpieczeniami",
    width: 640,
    height: 427,
  },
  {
    src: gallery26,
    alt: "Rozdzielnia z urządzeniami do pomiarów fotowoltaicznych",
    width: 640,
    height: 427,
  },
  {
    src: gallery27,
    alt: "Rozdzielnia z miernikami elektrycznymi",
    width: 640,
    height: 427,
  },
  {
    src: gallery28,
    alt: "Pomiary elektryczne instalacji",
    width: 640,
    height: 427,
  },
  {
    src: gallery29,
    alt: "Rozdzielnia z zabezpieczeniami elektrycznymi",
    width: 640,
    height: 427,
  },
  {
    src: gallery30,
    alt: "Instalacja elektryczna w trakcie pomiaru",
    width: 640,
    height: 427,
  },
  {
    src: gallery31,
    alt: "Sprawdzanie instalacji elektrycznej",
    width: 640,
    height: 427,
  },
  {
    src: gallery32,
    alt: "Instalacja paneli fotowoltaicznych na budynku",
    width: 640,
    height: 427,
  },
  {
    src: gallery33,
    alt: "Montaż systemu fotowoltaicznego",
    width: 640,
    height: 427,
  },
  {
    src: gallery34,
    alt: "Pomiary systemu fotowoltaicznego na dachu",
    width: 640,
    height: 427,
  },
  {
    src: gallery35,
    alt: "Testy paneli fotowoltaicznych",
    width: 640,
    height: 427,
  },
  {
    src: gallery36,
    alt: "Instalacja fotowoltaiczna na dachu budynku",
    width: 640,
    height: 427,
  },
  {
    src: gallery37,
    alt: "Rozdzielnia z miernikami i przewodami",
    width: 640,
    height: 427,
  },
  {
    src: gallery38,
    alt: "Pomiar prądu w rozdzielni fotowoltaicznej",
    width: 640,
    height: 427,
  },
  {
    src: gallery39,
    alt: "Urządzenie pomiarowe w rozdzielni fotowoltaicznej",
    width: 640,
    height: 427,
  },
  {
    src: gallery40,
    alt: "Rozdzielnia z urządzeniami fotowoltaicznymi",
    width: 640,
    height: 427,
  },
  {
    src: gallery41,
    alt: "Montaż paneli słonecznych na budynku mieszkalnym",
    width: 640,
    height: 427,
  },
  {
    src: gallery42,
    alt: "Urządzenie pomiarowe Sonel MPI-540PV",
    width: 640,
    height: 427,
  },
  {
    src: gallery43,
    alt: "Pomiary urządzeniem Sonel MPI-540PV",
    width: 640,
    height: 427,
  },
  {
    src: gallery44,
    alt: "Urządzenie Sonel MPI-540PV do pomiarów fotowoltaicznych",
    width: 640,
    height: 427,
  },
  {
    src: gallery45,
    alt: "Testowanie instalacji fotowoltaicznej z Sonel MPI-540PV",
    width: 640,
    height: 427,
  },
  {
    src: gallery46,
    alt: "Urządzenie Sonel MPI-540PV do testów instalacji",
    width: 640,
    height: 427,
  },
  {
    src: gallery47,
    alt: "Sprawdzanie instalacji fotowoltaicznej z urządzeniem Sonel",
    width: 640,
    height: 427,
  },
  {
    src: gallery48,
    alt: "Urządzenie do pomiarów Sonel MPI-540PV",
    width: 640,
    height: 427,
  },
  {
    src: gallery49,
    alt: "Testy elektryczne z Sonel MPI-540PV",
    width: 640,
    height: 427,
  },
  {
    src: gallery50,
    alt: "Pomiary elektryczne z Sonel MPI-540PV",
    width: 640,
    height: 427,
  },
  {
    src: gallery51,
    alt: "Termowizyjne badanie paneli fotowoltaicznych",
    width: 640,
    height: 427,
  },
  {
    src: gallery52,
    alt: "Termowizyjna analiza panelu fotowoltaicznego",
    width: 640,
    height: 427,
  },
  {
    src: gallery53,
    alt: "Termowizyjna kontrola systemu fotowoltaicznego",
    width: 640,
    height: 427,
  },
  {
    src: gallery54,
    alt: "Badanie termowizyjne instalacji fotowoltaicznej",
    width: 640,
    height: 427,
  },
  {
    src: gallery55,
    alt: "Panele fotowoltaiczne na dachu budynku",
    width: 640,
    height: 427,
  },
  {
    src: gallery60,
    alt: "Widok na instalację fotowoltaiczną na dachu",
    width: 640,
    height: 427,
  },
];

const images = [
  {
    src: gallery2,
    alt: "Panele fotowoltaiczne na dachu domu",
    width: 640,
    height: 427,
  },
  {
    src: gallery56,
    alt: "Instalacja paneli fotowoltaicznych na dachu",
    width: 640,
    height: 427,
  },
  {
    src: gallery57,
    alt: "Panele fotowoltaiczne na budynku przemysłowym",
    width: 640,
    height: 427,
  },
  {
    src: gallery58,
    alt: "Dom jednorodzinny z panelami fotowoltaicznymi",
    width: 640,
    height: 427,
  },
  {
    src: gallery59,
    alt: "Instalacja paneli słonecznych na budynku mieszkalnym",
    width: 640,
    height: 427,
  },
  {
    src: gallery43,
    alt: "Pomiary urządzeniem Sonel MPI-540PV",
    width: 640,
    height: 427,
  },
];

export { priceList, contactInfo, allImages, images };
